### ISSUE TITLE
Use EKS Addon to manage VPC CNI instead of being self-managed

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-eks#1132]
## Issue details

Currently, the EKS provider maintains a hardcoded copy of v1.16.0 of the VPC CNI manifest that is installed on all EKS clusters created/managed by this provider. This could lead to a version compatibility mismatch between the CNI and EKS cluster version. We should migrate to using the underlying aws.eks.Addon resource to manage the VPC CNI manifests on cluster. This will also remove the dependency on shelling out to `kubectl`.

This will also help mitigate #669, as the error occurs when we attempt to communicate directly with the Kubernetes API server.

This is planned feature work for the next major version release.

### Affected area/feature

eks.Cluster and eks.VpcCni

**Comment by flostadler** [comment]
Switching out the existing VPC CNI with the addon should be disruption free because the provider doesn't implement a delete operation for the VPC CNI.
EKS Addons adopt resources, so this should be transparent.

In terms of configuration options, almost all existing config options of the VPC CNI translate to configuration options of the addon. The exceptions are `securityContext` and `image` properties.

Those should work with the patch resources leveraging Kubernetes Server Side Apply. Currently building a prototype to confirm this.

**Comment by flostadler** [comment]
This is merged into the release branch now
