### ISSUE TITLE
Updates fail when autoScalingGroupTags & cloudFormationTags are both set and dupes exist

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi-eks#144]
Passing `autoScalingGroupTags: myTags` to `eks.Cluster.createNodeGroup` will fail on an update with the following message in the CF console: "You cannot have multiple tags with the same key name."
```
const cluster = new eks.Cluster("k8s-cluster", {
    vpcId: vpc.id,
    subnetIds: vpc.publicSubnetIds,
    deployDashboard: true,
    skipDefaultNodeGroup: true,
    tags: envTags
});

eksCluster.createNodeGroup(`k8s-${env}-ng`, {
        instanceType: "c5.2xlarge",
        desiredCapacity: 3,
        minSize: 1,
        maxSize: 3,
        instanceProfile: eksInstanceProfile,
        autoScalingGroupTags: {env: "dev"},
        cloudFormationTags: {env: "dev"}
    });
```

If you change the maxSize to 4 and run `pulumi up`, the update will fail with the aforementioned message.

**Comment by metral** [comment]
IIUC you added in `autoScalingGroupTags` _after_ an initial deployment without it set, but it did have the `cloudFormationTags` set, correct?

If I'm groking this correctly, then yes the CF console err message is right in that there are dupes of the keys trying to be set, because when an ASG is defined in the CF template, any tags defined for CF automatically get inherited into the ASG as well. Therefore, if you tried to add the same `{env: "dev"}` tags for `autoScalingGroupTags` after the initial deployment, which set the same tags in the `cloudFromationTags` and ASG already in the initial deployment, you'd encounter this error.

See this pic showing the inheritance of the tags in the CF on the left with `cloudFormationTags` set, also existing in the ASG on the right:

![image](https://user-images.githubusercontent.com/1112768/59150790-03bd6680-89de-11e9-961e-06840ee2358e.png)

The docs could be better here around pointing out the inheritance of CF tags in ASG's, so I'll open a fix to clear this up.

Please let us know if this is still an issue for you.

**Comment by kennyjwilli** [comment]
I can’t recall if I added them in after the initial deployment. I think I added them both at the same time, after the initial deployment. Is there a reason this duplicate keys problem couldn’t be handled by this library by removing duplicated keys from the ASG? This would avoid the problem altogether.
