### ISSUE TITLE
Subnet error with default cluster values

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-eks#311]
### Problem description

This example was working yesterday, and just started failing. I believe it's related to changes in the awsx library. 

- I saw an issue in the following Pulumi Program:
```ts
const cluster = new eks.Cluster("test", {
    minSize: 2,
    maxSize: 2,
    version: "1.14",
    instanceType: "m4.large",
    deployDashboard: false
});
```

### Errors & Logs

```
error: error creating EKS Cluster (test-eksCluster-0d74419): InvalidParameterException: Subnets specified must be in at least two different AZs
    status code: 400, request id: 4d6c0ec0-114b-4f18-9612-f2394172c86e
```

**Comment by metral** [comment]
Couple of questions:

- I'm presuming that there was no vpc being created, and it was defaulting to use the default vpc in the region. Is this right?
- What region was this in?

cc'ing @CyrusNajmabadi since I too started seeing this in EKS CI tests yesterday. Could any changes in awsx have led to this?

**Comment by lblackstone** [comment]
> * I'm presuming that there was no vpc being created, and it was defaulting to use the default vpc in the region. Is this right?

Right, I didn't specify anything besides the snippet I provided.

> What region was this in?

`us-west-2`

**Comment by metral** [comment]
It appears I was able to resolve this on my end. Turns out that in our dev account, we did recent cleanup earlier in the week and that must've removed resources, as we only had 1 of the default 4 subnets a default VPC creates.

The default vpc was recreated and tagged appropriately to prevent bot clean up.

@lblackstone can you test again in your dev account in us-west-2 and see if things are fixed on your end?

**Comment by lblackstone** [comment]
Yep, that seems to be working now. Will close this issue out now.
