### ISSUE TITLE
Support Elastic IP configuration for NodeGroup

### ISSUE THREAD

**Issue by aaronhayes** [pulumi/pulumi-eks#479]
### Problem description

I'd like to be able to set the IP addresses of my nodes; I need my nodes to be certain static IP addresses (registered as Elastic IPs) for security reasons. 

- I had trouble finding the information that I needed: <URL>
I'm not sure if this is currently supported.

**Comment by stack72** [comment]
Hi @aaronhayes 

I can't find any such functionality in the AWS cli - can you point me to something that shows this is supported? Maybe it's a new release?

Paul

**Comment by aaronhayes** [comment]
Hi @stack72 ,

I'm not sure if the AWS cli supports this, was hoping it did. But thinking through this a a little more, it's probably not the ideal solution. 
I think a NAT gateway used for all outbound communications with a static IP address; so nodes can be scaled up/down and not worry about the address.

**Comment by stack72** [comment]
Yeah so the way this would have to be managed is via the subnets that the node groups live on. They can either be private and fronted with Nat gateways or whatever else

This type of control is already in place today. If you want your nodegroups to assume the same network settings as your control plane then that happens by default.

Otherwise you can pass nodeSubnetIds to the nodegroup and this will override the control plane would have assigned by default

I hope this helps

Paul

**Comment by aaronhayes** [comment]
Thanks Paul

**Comment by stack72** [comment]
Any time! Feel free to open anything like this so we can talk things through
