### ISSUE TITLE
no resource plugin 'eks-v2.7.8' found in the workspace

### ISSUE THREAD

**Issue by landy** [pulumi/pulumi-eks#529]
I'm trying to create a EKS cluster from the dotnet package and when running `pulumi up` it throws error that the plugin `eks-v2.7.8` is missing. When I try to install the plugin with the suggested command it fails with 403 error.

my code:
```
open Pulumi.FSharp
open Pulumi.Eks


let infra () =
  let args = ClusterArgs()
  let cluster = Cluster("my-cluste", args)
  // Export the name of the bucket
  dict [("bucketName", cluster.Kubeconfig :> obj)]

[<EntryPoint>]
let main _ =
  Deployment.run infra
```

and packages in fsproj:
```
<ItemGroup>
    <PackageReference Include="Pulumi.Eks" Version="0.22.0" />
    <PackageReference Include="Pulumi.FSharp" Version="2.19.0" />
    <PackageReference Include="Pulumi.Aws" Version="3.*" />
  </ItemGroup>
```

global.json:
```
{
  "sdk": {
    "version": "3.1.402"
  }
}
```

errors:
pulumi up:
```
error: no resource plugin 'eks-v2.7.8' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource eks v2.7.8`
```
install plugin:
```
[resource plugin eks-2.7.8] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-eks-v2.7.8-darwin-amd64.tar.gz
```

**Comment by EvanBoyle** [comment]
@landy there is no eks release under that version. The latest version is `v0.22.0`. You can download the plugin with the following:

```shell
$ plugin install resource eks v0.22.0
```

Could you give that a try and see if that unblocks you? It's unclear why the program would request that version of the plugin.

**Comment by landy** [comment]
yeah I know, it was the first error message thas I saw to install 0.22.0 but then it started requesting the version 2.7.8

**Comment by justinvp** [comment]
For some reason the `version.txt` we emit in the `Pulumi.Eks` NuGet package (file used to determine the plugin to download) has `2.7.8` instead of `0.22.0`. Not sure why it's happening. `2.7.8` appears to be the version of `Pulumi.Kubernetes`. Not sure yet why that's being injected into `Pulumi.Eks`'s `version.txt`.

In the meantime, the workaround is to manually install the plugin as Evan suggests:

```
$ pulumi plugin install resource eks v0.22.0
```

**Comment by justinvp** [comment]
When we build, we get the following warnings:

```
/usr/local/share/dotnet/sdk/3.1.404/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/Users/user/.nuget/packages/pulumi.aws/3.29.1/contentFiles/any/netcoreapp3.1/version.txt' is not added because the package already contains file 'content/version.txt' [/Users/user/go/src/github.com/pulumi/pulumi-eks/dotnet/Pulumi.Eks.csproj]
/usr/local/share/dotnet/sdk/3.1.404/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/Users/user/.nuget/packages/pulumi.aws/3.29.1/contentFiles/any/netcoreapp3.1/version.txt' is not added because the package already contains file 'contentFiles/any/netcoreapp3.1/version.txt' [/Users/user/go/src/github.com/pulumi/pulumi-eks/dotnet/Pulumi.Eks.csproj]
/usr/local/share/dotnet/sdk/3.1.404/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/Users/user/go/src/github.com/pulumi/pulumi-eks/dotnet/version.txt' is not added because the package already contains file 'content/version.txt' [/Users/user/go/src/github.com/pulumi/pulumi-eks/dotnet/Pulumi.Eks.csproj]
/usr/local/share/dotnet/sdk/3.1.404/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/Users/user/go/src/github.com/pulumi/pulumi-eks/dotnet/version.txt' is not added because the package already contains file 'contentFiles/any/netcoreapp3.1/version.txt' [/Users/user/go/src/github.com/pulumi/pulumi-eks/dotnet/Pulumi.Eks.csproj]
    4 Warning(s)
```

It looks like it's including the `version.txt` from `Pulumi.Kubernetes` NuGet package, and then warning when it tries to add the `version.txt` from `Pulumi.Aws` and `version.txt` intended to be included.

Need to tell the csproj not to include the `version.txt` from other packages.

**Comment by justinvp** [comment]
I think there are two aspects to addressing this:

1. Stop including `version.txt` in our NuGet package's `contentFiles` to prevent it from being copied to the `contentFiles` of packages that reference our packages with `<PackageReference>`. We still want `version.txt` to end up in the package's `content` directory (as this is where our .NET language host looks for the file), but we don't need or want it in `contentFiles`. We can accomplish this by changing from using `<Content Include="version.txt" />` to include the file to `<None Include="version.txt" Pack="True" PackagePath="content" />`:

   ```diff
   -<Content Include="version.txt" />
   +<None Include="version.txt" Pack="True" PackagePath="content" />
   ```

   This way, we still have the file in the package's `content/version.txt` where the Pulumi .NET language host expects to find it, but it isn't included in `contentFiles` so it won't be included in any packages that reference the package.

2. Until our packages have made this change, we need to update the `.csproj` codegen when referencing our packages to exclude contentFiles, by adding `ExcludeAssets="contentFiles"` to the `<PackageReference>`. This way the current project's package won't include any of the referenced package's contentFiles. In the case of EKS, the generated code should look like:

   ```xml
     <ItemGroup>
       <PackageReference Include="Pulumi" Version="2.*" />
       <PackageReference Include="Pulumi.Aws" Version="3.*" ExcludeAssets="contentFiles" />
       <PackageReference Include="Pulumi.Kubernetes" Version="2.*" ExcludeAssets="contentFiles" />
     </ItemGroup>
   ```

   I don't think we want to add a blanket `ExcludeAssets="contentFiles"` to all package references, because it's possible someone might want to add a reference to a package and have its content files include. Aside from adding a new .NET option in the schema to control this, a simple solution would be to update the codegen to always add `ExcludeAssets="contentFiles"` to any reference that starts with `Pulumi.`.
