### ISSUE TITLE
add `capacityType` to Managed Node Group configuration options

### ISSUE THREAD

**Issue by tmehlinger** [pulumi/pulumi-eks#565]
My team is using Pulumi to configure EKS with Managed Node Groups to provide on-demand capacity. We would like to do configure spot capacity in MNGs as well but this is presently unsupported in the MNG resource because the resource doesn't have a `capacityType` input property: https://www.pulumi.com/docs/reference/pkg/eks/managednodegroup/#properties.

The AWS API documentation shows the option here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html#cfn-eks-nodegroup-capacitytype. Likewise, digging through the Terraform provider, it is supported there as well.

**Comment by michael-barker** [comment]
@tmehlinger You actually can set the `capacityType`. The documentation is a bit different from the current Pulumi EKS version. I was trying to set taints on a ManagedNodeGroup today and the documentation says the property should exist but it does not.

[eks.ManagedNodeGroupOptions](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/nodegroup.ts#L686) extends aws.eks.NodeGroupArgs which does have a [capacityType property](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/eks/nodeGroup.ts#L353-L356). I'm currently using `capacityType: SPOT` with a `ManagedNodeGroup`.

**Comment by leezen** [comment]
@tmehlinger One option you have is to use a [transformation](https://www.pulumi.com/docs/intro/concepts/resources/#transformations) to modify the underlying `NodeGroup`

**Comment by justinvp** [comment]
As @michael-barker says, in TypeScript `eks.ManagedNodeGroupOptions` extends `aws.eks.NodeGroupArgs` which does have a [`capacityType`](https://github.com/pulumi/pulumi-aws/blob/0b73446ce5361fcd9f313d7e5ac36e5668936d31/sdk/nodejs/eks/nodeGroup.ts#L386) property:

https://github.com/pulumi/pulumi-eks/blob/86861e6cb6091e97d08828a444bb70087a8701f3/nodejs/eks/nodegroup.ts#L686

However, this isn't available to the other languages because we manually copied the properties from `aws.eks.NodeGroupArgs` into the EKS schema, and `capacityType` must not have been present at the time we did that.

https://github.com/pulumi/pulumi-eks/blob/86861e6cb6091e97d08828a444bb70087a8701f3/provider/cmd/pulumi-gen-eks/main.go#L565-L676

Unfortunately, a transformation can't be used from Python, Go, or .NET, because transformations don't yet work across the multi-language boundary (this is tracked by https://github.com/pulumi/pulumi/issues/6948).

To address this, one simple fix would be to manually add `capacityType` to the schema (along with any other properties that are missing), so that it's available to Python, Go, and .NET.

A better solution would be to do something similar to what's done in the TypeScript implementation: as part of generating the EKS schema, load the AWS provider's schema and extract the `aws.eks.NodeGroup` input properties and insert them as input properties of the `eks.ManagedNodeGroup` component (omitting the same properties as omitted in the TS implementation). That way, we won't have to manually add any future input properties from `aws.eks.NodeGroup` -- they'd be included as inputs of `eks.ManagedNodeGroup` automatically the next time we bump the AWS provider dependency and regenerate the schema. If this is the approach we use, we should do a scrub of other args in this package to see if we need to do anything similar elsewhere.
