### ISSUE TITLE
Remove `provider` from cluster result

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-eks#602]
Until https://github.com/pulumi/pulumi/issues/7012 is addressed, the provider returned in the cluster result is unusable without creating resources within an apply. Users should just create a provider from the returned kubeconfig instead.

Until we can address the underlying issue, we should just remove this field and consider removing the AWS provider as well, although it is not clear if there is a comparable work around.

**Comment by benesch** [comment]
Yes, please! I advocated for something similar here: https://github.com/pulumi/pulumi-kubernetes/issues/1565#issuecomment-875233168

Now that you've made provider aliases work (https://github.com/pulumi/pulumi/issues/3979—thanks!), I think removing the `provider` field is actually viable. Previously, switching providers triggered a recreation of all dependent resources. At least it did when I tried.

**Comment by joeduffy** [comment]
Am I reading between the lines correctly that pulumi/pulumi#7012 won't be addressed soon?

**Comment by benesch** [comment]
I am just an eager observer, but my understanding is:

  * @t0yv0 is making awesome progress teaching `depends_on` to accept `Output[Resource]`. This is part of #7012, but not the part that matters for this issue. Nonetheless it was _the_ most painful part of multi-lang components in my experience, and it’s now fixed in Python. Seems like maybe another week or to for Go and C# support? The PRs are out for those languages. 
  * The part of #7012 that matters for this issue, making `provider` accept an `Output[ProviderResource]`, is tractable, but requires making a breaking change to the Node.js SDK. As far as I can see externally this is blocked on buy in that the breakage is worth it? But I suspect this is many weeks out at least because there aren’t any PRs out yet.

**Comment by justinvp** [comment]
> Users should just create a provider from the returned kubeconfig instead.

Here's an example of how to do this in Python:

```python
import json

from pulumi import ResourceOptions
from pulumi_eks import Cluster
from pulumi_kubernetes import Provider
from pulumi_kubernetes.core.v1 import Namespace

cluster = Cluster("test")

# Create a new Kubernetes Provider from the Cluster's kubeconfig:
provider = Provider("eks-k8s", kubeconfig=cluster.kubeconfig.apply(lambda k: json.dumps(k)))

# Use the provider:
namespace = Namespace("test", opts=ResourceOptions(provider=provider))
```
