### ISSUE TITLE
Tags aren't propagated to EC2 instances as part of a Managed Node Group

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-eks#635]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating a new Managed Node Group, I've specified in the `tags` property a tag. The specified tags aren't propagated to the EC2 instances created for the managed node group.

This may be related to #563

### Steps to reproduce

1. Use https://github.com/pulumi/pulumi-eks/tree/master/examples/managed-nodegroups as a starting point
2. Add tags to any ManagedNodeGroup (`managedNodeGroup2` has already one)
3. The resulting EC2 instance doesn't have the tag `org`

Expected: The EC2 instance for `managedNodeGroup2` has the specified tags
Actual: The EC2 instance for `managedNodeGroup2` doesn't have the specified tags

**Comment by miadabrin** [comment]
We have the same issue. To be clear in our case the tag does not exist on the ASG itself as well

**Comment by lukehoban** [comment]
Based on the details at https://docs.aws.amazon.com/eks/latest/userguide/eks-using-tags.html, I believe this is by design for EKS.  The tags applied to a managed node group are applied only to the managed node group, not to the resources managed by the node group.

> Amazon EKS managed node groups | Yes | No. Managed node group tags do not propagate to any other resources associated with the node group.
> -- | -- | --
> 


Later in that page, they note explicitly what you need to do for this scenario:

> *If you want to also tag the Amazon EC2 instances when creating a managed node group, create the managed node group using a launch template. For more information, see Tagging Amazon EC2 instances. If your instances already exist, you can manually tag the instances. For more information, see Tagging your resources in the Amazon EC2 User Guide for Linux Instances.

That approach should work naturally via the Managed Node Group support in `@pulumi/eks`.

Given that, I don't believe there is anything we can or should do in the `@pulumi/eks` layer here.
