### ISSUE TITLE
Support bottlerocket AMI Family on EKS managed node group

### ISSUE THREAD

**Issue by ZhiHanZ** [pulumi/pulumi-eks#638]
## Hello!

AWS 
AWS recently provided support to run bottlerocket natively on EKS managed node group. https://aws.amazon.com/blogs/containers/amazon-eks-adds-native-support-for-bottlerocket-in-managed-node-groups/ 
Does pulumi have plan to support it?
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by mikhailshilkov** [comment]
@ZhiHanZ Thank you for your question.

If I understand correctly, the it should be possible with the Pulumi AWS provider already by setting the right AMI and maybe user data. Since you opened the issue in this repo, I guess you are asking whether the `@pulumi/eks` package supports it.

I wonder if you tried setting AMI on the node group? Do you know what else does it take to enable bottlerocket?

**Comment by ZhiHanZ** [comment]
Hi @mikhailshilkov , thank you for response. 
Here I think currently pulumi/eks only support AL2_x86_64 | AL2_x86_64_GPU | AL2_ARM_64 for amiType (https://github.com/pulumi/pulumi-eks/blob/master/sdk/go/eks/managedNodeGroup.go#L47),
and in aws official doc (https://docs.aws.amazon.com/eks/latest/APIReference/API_Nodegroup.html), they also support 
BOTTLEROCKET_ARM_64 | BOTTLEROCKET_x86_64 amiType, so I am wondering about whether here is a plan to support it.

**Comment by mikhailshilkov** [comment]
Good point. However, this list is just a textual description which shouldn't restrict which values you can pass there. We should probably adjust it [here](https://github.com/pulumi/pulumi-eks/blob/e03751425604b5193c00cd2f8858d9b16f7901f0/provider/cmd/pulumi-gen-eks/main.go#L621-L623) but meanwhile you could try passing a bottlerocket value. I'm curious if it would just work.

**Comment by ronaldour** [comment]
It actually restricts the values that can be used. It fails with error `expected ami_type to be one of [AL2_x86_64 AL2_x86_64_GPU AL2_ARM_64 CUSTOM], got BOTTLEROCKET_x86_64. Examine values at 'NodeGroup.AmiType'.` 
I think this should be updated to support those AMI types, otherwise we need to create a custom launch template to use Bottlerocket AMIs

**Comment by michael-barker** [comment]
I was able to use the Bottlerocket AMI types by updating to the latest Pulumi dependencies. I believe specifically the pulumi-aws dependency is what enables this.
