### ISSUE TITLE
Failures to kubectl apply

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-eks#65]
We periodically see CI failures due to the below, and have also heard user reports of seeing similar.  We should figure out what is needed to be robust against this:

```
[ ks/nodejs/eks/examples/cluster ]   pulumi-nodejs:dynamic:Resource (cluster2-vpc-cni):
[ ks/nodejs/eks/examples/cluster ]     error: Plan apply failed: Command failed: kubectl apply -f /tmp/tmp-12841ugyvSLxyVH46.tmp
[ ks/nodejs/eks/examples/cluster ]     error: unable to recognize "/tmp/tmp-12841ugyvSLxyVH46.tmp": Get https://AA28F18B717D67BED6FEC1BFB8B2C64F.sk1.eu-west-1.eks.amazonaws.com/api?timeout=32s: dial tcp 54.154.206.100:443: i/o timeout
```

**Comment by metral** [comment]
Is there a way to repro this issue?

**Comment by lukehoban** [comment]
@metral not that I know of - this just seems to happen “sometimes”. Many users have reported hitting this.

**Comment by hausdorff** [comment]
@lukehoban @metral I think we should consider having an (undocumented?) `invoke` exposed through the Pulumi Kubernetes SDK that `apply`'s a YAML. Especially given that we just spent two engineer-days on this precise issue, it strikes me as vastly preferable to just have a hidden escape hatch that goes through the provider, rather than going through an entire second client in a hacky shell-out.

Thoughts?

**Comment by lukehoban** [comment]
We have not been able to root cause the specific failure here - but believe that adding the mechanism in https://github.com/pulumi/pulumi-kubernetes/issues/509 will provide a more robust approach to use here.  Moving this to M23 to track along with that work.
