### ISSUE TITLE
eks default_4_35_0  error: no resource plugin 'eks-v4.35.0' found in the workspace

### ISSUE THREAD

**Issue by urit** [pulumi/pulumi-eks#666]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I run `pulumi up` using eks and I get

eks default_4_35_0  error: no resource plugin 'eks-v4.35.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource eks v4.35.0`
 
There is no such plugin, max version is `v0.37.1`

**Comment by justinvp** [comment]
Hi @urit, I haven't been able to reproduce the issue. What is the output of running `pulumi about`?

Also, if you run `pulumi up` with [verbose logging](https://www.pulumi.com/docs/troubleshooting/#verbose-logging) (e.g. `pulumi up --logtostderr -v=9 2> out.txt`), would you be able to share the lines from `plugins.go`?

If you'd rather not post the output here, happy to accept that via DM in the Community Slack (my username is `justin`).

**Comment by urit** [comment]
Hi @justinvp Thanks for your help

this is the result
[out.txt](https://github.com/pulumi/pulumi-eks/files/8127080/out.txt)

I tried to remove all the python packages as well as the plugin and start fresh

**Comment by urit** [comment]
Remove some of the irrelevant resources
Still fails :( 
[out.txt](https://github.com/pulumi/pulumi-eks/files/8127208/out.txt)

**Comment by justinvp** [comment]
Thanks for the logs. What is the output of running `pulumi about`?

**Comment by justinvp** [comment]
Still haven't gotten to the bottom of this and haven't been able to reproduce the behavior locally. For some reason, when registering the request to create the Cluster resource, the engine is receiving the AWS version rather than the EKS version.

I'd be interested to know what is outputted by adding the following to the Pulumi program:

```python
from pulumi_eks import _utilities
print(f"pulumi_eks version: {_utilities.get_version()}")
```

Until we've determined the root cause and addressed the issue, one possible way to workaround this is by specifying the version explicitly when creating any resource from the `pulumi-eks` package, e.g.:

```python
mycluster = eks.Cluster("mycluster", opts=pulumi.ResourceOptions(version="0.37.1"))
```

**Comment by csakshaug** [comment]
@urit Which OS / Machine do you have?

I have the same problem, I wonder if it is related to that I have MacBook with M1. 

Working when I am running on Linux other Intel

**Comment by urit** [comment]
@csakshaug MacBook with M1

**Comment by csakshaug** [comment]
It was easier/better to get more information on Linux but I pointed my to my node/npm installation in the "shell", first I was thinking it was related to the M1 but for me at least was that my node installation on the "osx shell" was not working. 

I was also checking and fixing go.mod etc first since our stack is based on go. It worked with `node:v18.0.0 and npm:v8.6.0 and go version go1.18.1 darwin/arm64`

**Comment by t0yv0** [comment]
Closing this as stale, please open a new issue with a repro if still having trouble. Thanks!
