### ISSUE TITLE
ConfigMap with multiple datafiles

### ISSUE THREAD

**Issue by siddhubp** [pulumi/pulumi-eks#741]
## Hello!

I have a requirement to create a configmap that has multiple files. I can't find any way to do it iteratively using Pulumi.
I will specifically focus on the data section of the configmap. 
```
data: {
   'file1': fs.readFileSync('fileLocation/file1').toString(),
   'file2': fs.readFileSync('fileLocation/file2').toString(),
   'file3': fs.readFileSync('fileLocation/file3').toString(),
... (i have 25 files). I also have multiple configMaps like this.
```

I also tried by creating a loop, to go over the file name and filecontent but cannot generate data section like the one above and somehow ends up being just a string which messes up the configmap.

Any suggestions?

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Affected area/feature
pulumi-eks/configmap

**Comment by viveklak** [comment]
This seems to not be a pulumi problem since you are essentially just building a generic config map? Have you considered looking at the pulumi/kubernetes support for ConfigFile or ConfigGroup? It should let you define the configmaps in yaml using whatever tool you are familiar with. Pulumi will deploy and manage the corresponding resources for you.
