### ISSUE TITLE
Investigate the options of removing the need for CloudFormation in NodeGroups

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-eks#750]
The cloudformation template is for the creation of an Autoscaling group - we can handle this via pulumi-aws ASG and be able to expose all of the options available in the ASG. We can make this property can either pass in an a user specified ASG or they can build the properties of the ASG automatically

@roothorp / @stack72 to come up with a design doc around this

**Comment by jaxxstorm** [comment]
A little bit of backstory here.

My recollection for us implementing the nodegroups as a cloudformation stack was because it was the only way of refreshing an ASG without interrupting the nodes.

However, `InstanceRefresh` properties have been added to the ASG resource: https://www.pulumi.com/registry/packages/aws/api-docs/autoscaling/group/#instance_refresh_python

So this isn't really necessary
